 apiVersion: v1
 kind: Service
 metadata:
   name: logproxy-node-deployment
 spec:
   ports:
   - port: 8080
     targetPort: 8080
     name: http
   - port: 514
     targetPort: 514
     name: syslogclient
   selector:
     app: logproxy
   type: NodePort
   sessionAffinity: None
   externalTrafficPolicy: Local